cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - build
  policy: pull

stages:
  - configure
  - format
  - build
  - test

Cmake configure:
  stage: configure
  image: registry.gitlab.akhcheck.ru/pir/rang/ci:latest
  tags:
    - common
  cache:
    <<: *global_cache
    policy: pull-push
  before_script:
    - mkdir -p build/.cmake/api/v1/query
    - touch build/.cmake/api/v1/query/codemodel-v2
  script:
    - cmake -Bbuild

Check formatting of sources:
  stage: format
  image: registry.gitlab.akhcheck.ru/pir/rang/ci:latest
  tags:
    - common
  cache:
    <<: *global_cache
    policy: pull
  script:
    - python3 ci/extract_sources.py rang | xargs -n1 clang-format --dry-run -Werror --verbose

Build:
  stage: build
  image: registry.gitlab.akhcheck.ru/pir/rang/ci:latest
  tags:
    - common
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - cmake --build build
  artifacts:
    paths:
      - build/rang

Test:
  stage: test
  image: registry.gitlab.akhcheck.ru/pir/rang/ci:latest
  tags:
    - common
  cache: 
    <<: *global_cache
    policy: pull
  script:
    - build/rang
