cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - build
  policy: pull

stages:
  - format
  - build
  - test

Check formatting of sources:
  stage: format
  image: registry.gitlab.akhcheck.ru/pir/rang/ci:latest
  tags:
    - common
  script:
    - clang-format -Werror --dry-run --verbose $(find src include test -type f -name '*.cpp' -or -name '*.hpp')

Build:
  stage: build
  image: registry.gitlab.akhcheck.ru/pir/rang/ci:latest
  tags:
    - common
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - cmake -Bbuild -DENABLE_TESTING=ON
    - cmake --build build
  artifacts:
    paths:
      - build/rang

Test:
  stage: test
  image: registry.gitlab.akhcheck.ru/pir/rang/ci:latest
  tags:
    - common
  cache:
    <<: *global_cache
    policy: pull
  variables:
    TERM: "xterm-256color"
  script:
    - cd build && make test
  artifacts:
    when: always
    paths:
      - build/Testing/*
    reports:
      junit:
        - build/test/report/*.xml
