cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - build
  policy: pull

stages:
  - build
  - format
  - test

Build:
  stage: build
  image: registry.gitlab.akhcheck.ru/pir/rang/ci:latest
  tags:
    - common
  cache:
    <<: *global_cache
    policy: pull-push
  before_script:
    - mkdir -p build/.cmake/api/v1/query
    - touch build/.cmake/api/v1/query/codemodel-v2
  script:
    - cmake -Bbuild -DENABLE_TESTING=ON
    - cmake --build build
  artifacts:
    paths:
      - build/rang

Check formatting of sources:
  stage: format
  image: registry.gitlab.akhcheck.ru/pir/rang/ci:latest
  tags:
    - common
  cache:
    <<: *global_cache
    policy: pull
  script:
    - python3 ci/extract_sources.py rang | xargs -n1 clang-format --dry-run -Werror --verbose
    - python3 ci/extract_sources.py tests | xargs -n1 clang-format --dry-run -Werror --verbose

Test:
  stage: test
  image: registry.gitlab.akhcheck.ru/pir/rang/ci:latest
  tags:
    - common
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd build && make test
  artifacts:
    when: always
    paths:
      - build/test/report.xml
    reports:
      junit: build/test/report.xml
